In [11]:
first_list = [i for i in range(10)]
second_list = [ i**2 for i in first_list if i%2==0 ]
second_list

[0, 4, 16, 36, 64]

In [12]:
first_list = []
for i in range(10):
    first_list.append(i)
second_list = []
for i in first_list:
    if ( i%2 == 0 ):
        second_list.append(i**2)
second_list
        

[0, 4, 16, 36, 64]

In [17]:
import numpy as np
a = np.array([0, 1, 2])
M = np.ones((3, 3))
M + a


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [18]:
import numpy as np
b = np.array([1, 2, 3, 4, 5])
np.tile(b.reshape(5, 1), (1, 4))

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5]])

In [20]:
import numpy as np
x = np.array([1, 2, 3])
x[1]

2

In [24]:
import numpy as np
time = np.arange(0, 10, 0.1)  # time values of wave 
x = np.sin(time)          	    # Amplitude of wave
x

array([ 0.        ,  0.09983342,  0.19866933,  0.29552021,  0.38941834,
        0.47942554,  0.56464247,  0.64421769,  0.71735609,  0.78332691,
        0.84147098,  0.89120736,  0.93203909,  0.96355819,  0.98544973,
        0.99749499,  0.9995736 ,  0.99166481,  0.97384763,  0.94630009,
        0.90929743,  0.86320937,  0.8084964 ,  0.74570521,  0.67546318,
        0.59847214,  0.51550137,  0.42737988,  0.33498815,  0.23924933,
        0.14112001,  0.04158066, -0.05837414, -0.15774569, -0.2555411 ,
       -0.35078323, -0.44252044, -0.52983614, -0.61185789, -0.68776616,
       -0.7568025 , -0.81827711, -0.87157577, -0.91616594, -0.95160207,
       -0.97753012, -0.993691  , -0.99992326, -0.99616461, -0.98245261,
       -0.95892427, -0.92581468, -0.88345466, -0.83226744, -0.77276449,
       -0.70554033, -0.63126664, -0.55068554, -0.46460218, -0.37387666,
       -0.2794155 , -0.1821625 , -0.0830894 ,  0.0168139 ,  0.1165492 ,
        0.21511999,  0.31154136,  0.40484992,  0.49411335,  0.57

In [25]:
word = 'Python'
word[1]

'y'

In [29]:
mybirds =["Parrot", "Sparrow", "Crow", "Eagle"] 
mybirds.insert(1,"Crow")  
mybirds

['Parrot', 'Crow', 'Sparrow', 'Crow', 'Eagle']

In [32]:
import pandas as pd
myseries2 = pd.Series([1, -3, 5, 20], index =["a", "b", "c", "d"]) 
myseries2[2:3]

c    5
dtype: int64

In [43]:
numbers = [i for i in range(1,11) ]
print(numbers)
del numbers[-2]
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 10]


In [66]:
a = 3
id(a)
b = 6
print(a)
print(id(a))
id(a)
a = b 
id(a)
print(a)
print(id(a))


3
140348383838512
6
140348383838608


In [75]:
n = 4 
myfile = open('week.txt')
for k, observation in enumerate(myfile): 
        if k % n==0: 
            print("Sampling rows: " + str(k) + ", Retrieved data " + observation)


Sampling rows: 0, Retrieved data sunday

Sampling rows: 4, Retrieved data thursday



In [82]:
import pandas as pd
# Create dataframe for students
df=pd.DataFrame({'id':[58,59,60,61],
                 'name':['sravan','jyothika','preethi','srinadh'],
                 'age':[22,21,22,23],
                 'subjects':['java','php','sql','r/python']})
# Display dataframe
print(df)
df.reset_index(drop=True,inplace=True)
df.
print(df)

   id      name  age  subjects
0  58    sravan   22      java
1  59  jyothika   21       php
2  60   preethi   22       sql
3  61   srinadh   23  r/python
   id      name  age  subjects
0  58    sravan   22      java
1  59  jyothika   21       php
2  60   preethi   22       sql
3  61   srinadh   23  r/python


In [116]:
from numpy import random
print("""
=================
array of 1 to 100
=================
""")
one_to_hunderd = [_ for _ in range(1,101)]
print(one_to_hunderd)
print("""
===================
four random numbers
===================
""")
for _ in range(4):
    print(one_to_hunderd[random.randint(100)])


array of 1 to 100

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

four random numbers

22
11
33
77
